### ISSUE TITLE
Failed building wheel for editdispy

### ISSUE THREAD

**Issue by erikhonda** [mammothb/editdistpy#7]
Hi,

I am trying to install symspellpy in python 3.9 and I get the error: Failed building wheel for editdistpy. Is that because editdistpy is not supported in any python versions > 3.8?

**Comment by mammothb** [comment]
@erikhonda I have bumped the supported Python version. Please try and install v0.1.4 `pip install editdistpy==0.1.4` and let me know if you still encounter errors

**Comment by mammothb** [comment]
![ccUjfXOwDz](https://github.com/mammothb/editdistpy/assets/7960706/864d0600-e9ef-4631-a727-34636b1cec4e)
Tested on my own machine and I was able to install it

**Comment by erikhonda** [comment]
Thank you it worked!
